  # This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Coverage

on:
  pull_request:
    branches: [ stable/yoga-m3 ]

env:
  UPPER_CONSTRAINTS_FILE: https://raw.githubusercontent.com/sapcc/requirements/stable/yoga-m3/upper-constraints.txt
  VIRTUALENV_PIP: "20.2.3"

jobs:
  build:

    #runs-on: ubuntu-latest
    #issue https://github.com/actions/setup-python/issues/544
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        python: [3.8.14]
        tox-env: [coverage]
    env:
      TOXENV: ${{ matrix.tox-env }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install Tox and any other packages
        run: |
          pip install tox
      - name: Running Tox
        run: tox
      - name: Comment coverage report
        uses: machine-learning-apps/pr-comment@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          path: pytest-coverage.txt

