  # This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Unit Tests

on:
  push:
    branches: [ stable/ussuri-m3 ]
  pull_request:
    branches: [ stable/ussuri-m3 ]

env:
  UPPER_CONSTRAINTS_FILE: https://raw.githubusercontent.com/sapcc/requirements/stable/ussuri-m3/upper-constraints.txt
  VIRTUALENV_PIP: "20.2.3"

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python: [3.6.15]
        tox-env: [unit,pep8,pip-missing-reqs]
    env:
      TOXENV: ${{ matrix.tox-env }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install Tox and any other packages
        run: |
          pip install tox
      - name: Running Tox
        run: tox

